### PR TITLE
Fix documentation

### PR DESCRIPTION
**Pull request by frederikbosch**
Missing letter, request-headers is plural.

### CODE REVIEW

**Comment by aelsabbahy** [comment]
Good catch, thanks!

**Comment by frederikbosch** [comment]
Thank you, great library!

**Comment by aelsabbahy** [comment]
Out of curiosity does the whole request-headers vs header thing seem inconsistent?

They were two different PRs by two contributors.. wondering if both should be normalized to "*headers"

**Comment by frederikbosch** [comment]
I agree. I would choose for either singular or plural and not use them interchangeably.

**Comment by frederikbosch** [comment]
What also is worth mentioning, or maybe I should create a PR for this, is that the host header is ignored, together with some headers. See [this line in net/http in the go library](https://github.com/golang/go/blob/master/src/net/http/request.go#L94).

**Pull request merged**
