### PR TITLE
Rename "alpha" -> "community"

### PR DESCRIPTION
**Pull request by aelsabbahy**
##### Checklist

- [x] `make test-all` (UNIX) passes. CI will also test this
- [x] unit and/or integration tests are included (if applicable)
- [x] documentation is changed or added (if applicable)

### Description of change

Rename alpha to community as discussed in #651 

@petemounce would love a quick review on this. It's just a naive `s/alpha/community/g` + file rename approach that I took and the build is green. Please let me know if there's anything I missed or if I renamed anything I wasn't supposed to =).

### CODE REVIEW

**Comment by petemounce** [comment]
Is there mention of GOSS_USE_ALPHA changing?

As far as I remember there is no automated coverage for the messaging part. I'll check that over here over the next few days.

What are your thoughts on:

* naming the binaries _without_ the suffix
* ... but keeping the messaging
* ... and keeping the must-use-flag-or-environment-variable awareness-need

?

Speaking for myself, dealing with a binary that is differently named across platforms requires an uncomfortable edge case in a few places that I would prefer to avoid.

Regardless of the precise nature of the change here, I'd like it if this were delayed until 0.4 because it is a breaking change.

**Comment by aelsabbahy** [comment]
I'm fine with the changes you mentioned. Can you submit a PR with how you'd like this to work.

I won't merge the PR until v4 is merged (hopefully late dec, early Jan)

**Comment by aelsabbahy** [comment]
Closing this in favor of @petemounce solution

**Comment by aelsabbahy** [comment]
Forgot to mention, when creating a PR for this, please create against the v4 branch

**Comment by aelsabbahy** [comment]
Do you happen to have an ARM macbook by any chance? Guessing the goss binary would need both arm and amd64

**Comment by petemounce** [comment]
I'm gonna take a look at this over the next few days. Sadly, no, I don't have an ARM macbook. I'll branch from v4.

**Pull request closed without merging**
