### PR TITLE
Use GOSS_FILE environment variable for dgoss

### PR DESCRIPTION
**Pull request by jfcastroluis**
Allows use `GOSS_FILE` environment variable for `dgoss`. If not defined then use `goss.yaml` as it's now.

Only set the filename to copy into the container. In the container the name is `goss.yaml` to avoid more changes in the script.

### CODE REVIEW

**Comment by jfcastroluis** [comment]
Yes, sorry :man_facepalming:
It's already fixed.

**Comment by aelsabbahy** [comment]
Sorry for the late response on this. Looks good to me, can you resolve the conflict and add the new variable to the dgoss README?

Aside from that, good to go.

**Comment by jfcastroluis** [comment]
I hope it's ready to merge. Let me know any change that I should do. Thanks.

**Comment by aelsabbahy** [comment]
LGTM! Thank you for your contribution.

**Pull request merged**
