### PR TITLE
Add a silent output

### PR DESCRIPTION
**Pull request by ouroboros8**
When using goss as a helathchecking endpoint, it may be desirable to
suppress verbose test output so that potential malicious entities can't
scrape healthcheck endpoints for system information.

Add the `silent` output, which simply checks whether any tests have
failed and returns 1 or 0 accordingly, without printing any output.

### CODE REVIEW

**Comment by aelsabbahy** [comment]
Awesome! Code looks good, can you also update the documentation as part of this pull request.

**Comment by ouroboros8** [comment]
Oh of course! My bad.

**Comment by ouroboros8** [comment]
I've added some one-line output descriptions. They're maybe a bit long, but I thought it was worth expanding on the use-case, since it's perhaps non-obvious.

**Comment by aelsabbahy** [comment]
I'll merge/release with next release. Thanks :+1:

**Pull request merged**
