### PR TITLE
Steal regexMatch from consul-template

### PR DESCRIPTION
**Pull request by blalor**
Makes it possible to do pattern-based template blocks.

### CODE REVIEW

**Comment by aelsabbahy** [comment]
Love it :+1: 

I'll merge/release this with the next release.

**Comment by blalor** [comment]
I should have mentioned that I stole this verbatim from [consul-template](https://github.com/hashicorp/consul-template/blob/v0.18.2/template/funcs.go#L829-L837).

I didn't have time tackle writing tests for `template.go` as part of this commit, but I'd like to see that happen, as I think more functions will probably get contributed. :-)

**Comment by blalor** [comment]
@aelsabbahy any idea when the next release will land?

**Comment by aelsabbahy** [comment]
Sometime later this week, been out on vacation.

**Comment by blalor** [comment]
👍

**Pull request merged**
