### PR TITLE
Feature/dgoss accept gossfile

### PR DESCRIPTION
**Pull request by kizzie**
Can use the --gossfile flag to pass in an alternate goss file to the edit or run commands. Makes life easier for when testing many docker containers with this!

### CODE REVIEW

**Comment by aelsabbahy** [comment]
Nice! It should also support the `goss_wait.yaml` file for it to be complete.

**Comment by kizzie** [comment]
Shall have a play when I get a moment - not used the wait part of the library yet :)

**Comment by aelsabbahy** [comment]
Hey @kizzie any update on this?

**Comment by kizzie** [comment]
Ooh no, I had completely forgotten about it. Shall have a look monday and see if I can remember what I was doing with it. Sorry about that!

**Comment by kizzie** [comment]
Hmm, looks like I'll have to do a lot of reading, going to close this until I've had time to rethink it!

**Comment by aelsabbahy** [comment]
No biggie, thanks for the update and the contributions so far.

**Pull request closed without merging**
