### PR TITLE
Update codegangsta/cli dependency to v1.16.0

### LINKED ISSUE #77: Update to more recent version of codegangsta/cli
When updating `glide.yaml` to use `cli` version 1.2.0 and attempting to build `goss`, I get the following error:
```
# github.com/aelsabbahy/goss
../../add.go:19: c.Duration undefined (type *cli.Context has no field or method Duration)
../../validate.go:26: c.GlobalIsSet undefined (type *cli.Context has no field or method GlobalIsSet)
```
Distributive uses a more recent version, so I can't take advantage of certain paths in `goss` code until this is fixed. I'll look into it. 

For reference, the current pinned commit is from 2015:
```
$ git show 70e3fa51ebed95df8c0fbe1519c1c1f9bc16bb13
commit 70e3fa51ebed95df8c0fbe1519c1c1f9bc16bb13
Merge: f445c89 3463964
Author: Jesse Szwedko <jesse.szwedko@gmail.com>
Date:   Thu Oct 29 20:11:27 2015 -0700
```

### PR DESCRIPTION
**Pull request by siddharthist**
Hopefully fixes #77

### CODE REVIEW

**Comment by aelsabbahy** [comment]
Haven't had time to look into this, or why it failed silently, but looking at the build output:
```
[ERROR] Failed to set version to 1.16.0: exit status 1
[WARN] Failed to set version on github.com/codegangsta/cli to 1.16.0: exit status 1
```

**Comment by siddharthist** [comment]
@aelsabbahy Maybe it's because it caches the dependencies? It works fine for me locally.

**Comment by aelsabbahy** [comment]
I haven't had time to follow up on this. Basically, it looks like this PR is running into the following glide bug:
https://github.com/Masterminds/glide/issues/40

**Comment by aelsabbahy** [comment]
Sorry for the long delay on this.

**Comment by siddharthist** [comment]
@aelsabbahy No problem, I appreciate your help!

**Pull request closed without merging**
