### PR TITLE
V4

### LINKED ISSUE #220: Clarify kernel-param value as string
Clarify the value is a string, to avoid users doing something like this.
```
KernelParam: net.ipv4.ip_forward: value:
Expected
    <string>: 0
to equal
    <int>: 0
```

### LINKED ISSUE #262: Either drop file/size from add/autoadd OR add md5 and sha to it.
Need to make a decision on which one of these attributes are included in add and which are not:
* Size
* md5
* sha256

### LINKED ISSUE #443: Check for mount options doesn't work
I'm trying to check my mount points with goss. It reports an error about missing mount options but the options are there.
```
$ cat mounts.yml
mount:
  /zpool/media/download:
    exists: true
    opts:
      - rw
      - relatime
      - posixacl
    source: zpool/media/download
    filesystem: zfs
  /home:
    exists: true
    opts:
      - rw
      - noatime
      - compress=zstd
      - ssd
      - discard
      - subvol=@home
    source: /dev/mapper/cryptroot
    filesystem: btrfs
$ goss -g mounts.yml validate -f tap
1..8
ok 1 - Mount: /home: exists: matches expectation: [true]
not ok 2 - Mount: /home: opts: doesn't match, expect: [["rw","noatime","compress=zstd","ssd","discard","subvol=@home"]] found: [["rw","noatime"]]
ok 3 - Mount: /home: source: matches expectation: ["/dev/mapper/cryptroot"]
ok 4 - Mount: /home: filesystem: matches expectation: ["btrfs"]
ok 5 - Mount: /zpool/media/download: exists: matches expectation: [true]
not ok 6 - Mount: /zpool/media/download: opts: doesn't match, expect: [["rw","relatime","posixacl"]] found: [["rw","relatime"]]
ok 7 - Mount: /zpool/media/download: source: matches expectation: ["zpool/media/download"]
ok 8 - Mount: /zpool/media/download: filesystem: matches expectation: ["zfs"]
$ goss -v
goss version v0.3.7
```

Any idea what I'm doing wrong?

### LINKED ISSUE #451: add process misreads process status
For several processes on my RHEL 7.3 server, goss seems to misrecord the statuses of processes... 

As a test, I pipe every process in ps into a goss add process command...
```
for p in $(ps -ef | grep -v '\[' | cut -b49- | cut -d" " -f1 | cut -d: -f1 | rev | cut -d/ -f1 | rev |sort -u); do 
  ../goss a process ${p}
done
```
Apart from the fluff (CMD from ps header, and ps, cut, rev, sort used in the command above), one would expect all these processes to be actual running processes.   Yet, goss reports several of them as **NOT** running.

If I take just systemd processes as an example:
```
ps -ef | grep systemd
root         1     0  0 May21 ?        00:00:51 /usr/lib/systemd/systemd --switched-root --system --deserialize 21
root       898     1  0 May21 ?        00:01:01 /usr/lib/systemd/systemd-journald
root       932     1  0 May21 ?        00:00:00 /usr/lib/systemd/systemd-udevd
dbus      2353     1  0 May21 ?        00:00:23 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
root      2383     1  0 May21 ?        00:00:08 /usr/lib/systemd/systemd-logind
```
We see 4 processes all running since May 21.   If we examine the goss.yaml file we see this:
```
grep -A1 systemd goss.yaml
  systemd:            
    running: true     
  systemd-journald:   
    running: false    
  systemd-logind:     
    running: true     
  systemd-udevd:      
    running: true
```
3 of the 4 are listed as running, but even though systemd-journald is running, it is reported as false...

Whatever is happening is consistent, in the sense that validation will pass confirming "systemd-journald" is not running when goss re-executes.

There are a few other processes (excluding ps, cut, rev, sort from the command that fed goss) from a vendor product on my system that similarly report as running false when they are actually running...   

Any idea what is happening to cause this strange behavior?

[This is using v0.3.7 AMD64]

### LINKED ISSUE #483: Expose actual command stdout / stderr on the goss test result
It would be nice to be able to opt into exposing the `stdout` that is compared to a regex / etc. in a `command` resource. This is a super trivial example, but suppose I wanted to test how many files are in a folder, and ensure that the number is greater than 3:

```
  "NUMAPP=$(expr $(ls -l /apps | wc -l) - 1); if [ $NUMAPP -ge 3 ]; then echo success: $NUMAPP; else echo fail: $NUMAPP; fi":
    title: apps_deployed_gt_3
    exit-status: 0
    stdout: [
      "/^success/"
    ]
    stderr: []
```

It would be nice if the stdout (i.e. `success: 4`) and/or stderr could be returned in the lengthy / verbose test output (i.e. JSON, documentation, etc.).

### LINKED ISSUE #538: Feature Request: Improve gomega matchers
**Describe the feature:**

Improve gomega matchers.

**Describe the solution you'd like**

1. Allow transforms. For example the following should work (fixes #350)
```yaml
kernel-param:
  net.core.somaxconn:
    value:
      gt: 5000
```

2. Add more gomega matchers, for example, the matchallelements matcher for slices.
https://onsi.github.io/gomega/#gstruct-testing-complex-data-types

### PR DESCRIPTION
**Pull request by aelsabbahy**
##### Checklist

- [ ] `make test-all` (UNIX) passes. CI will also test this
- [ ] unit and/or integration tests are included (if applicable)
- [ ] documentation is changed or added (if applicable)
- [ ] document breaking change (service enabled and others..)
- [ ] Fix issue with mount splitting and quoting

### Description of change

Merge v4 changes:
closes #443
closes #538
closes #483
closes #451
closes #262
closes #220

### CODE REVIEW

**Comment by aelsabbahy** [comment]
@petemounce https://travis-ci.com/github/aelsabbahy/goss/jobs/464664327

Any thoughts on this, seems the OSX build is failing now :(

**Comment by aelsabbahy** [comment]
@petemounce nevermind.. a little trial and error, changing the OSX image fixed it :man_shrugging:

**Comment by aelsabbahy** [comment]
@petemounce This PR is pretty much done outside of documentation on breaking changes.

If you or anyone else you know wants to build/test this prior to release let me now.. otherwise. I'll cut the release within a week and hope for the best.

My next major goss effort is.. complete rewrite of integration tests to gain more confidence with major releases like this.

**Comment by petemounce** [comment]
Seems very reasonable to me. I won't have an opportunity to touch goss in a work context for two weeks; I say :shipit:.

I'm happy to coordinate effort with you on the integration tests; of there's no open issue, let's make one and we can talk through and plan there? I'd also be happy to video conference sometime.

**Comment by berney** [comment]
@aelsabbahy Can this be revisited?

**Comment by berney** [comment]
@aelsabbahy anything I can do to help with getting v4 released?

**Pull request closed without merging**
