### PR TITLE
 integration tests repaired

### PR DESCRIPTION
**Pull request by gindelmer**
- corrected status code for http://google.com change to 302
- apache2 version in wheezy changed

### CODE REVIEW

**Comment by aelsabbahy** [comment]
I'm confused by this pull request. I just retriggered the latest master build and it seems to be working fine in travis.

**Comment by gindelmer** [comment]
I'm confused to. I run make on a machine with location in germany. The integration tests failed for me with wrong status code from google.com:

``` bash
make test-all
.
.
+ docker_exec diff -wu /goss/centos7/goss-expected.yaml /goss/centos7/goss-generated-amd64.yaml
+ docker exec goss_int_test_centos7_amd64 diff -wu /goss/centos7/goss-expected.yaml /goss/centos7/goss-generated-amd64.yaml
--- /goss/centos7/goss-expected.yaml    2017-03-25 20:26:33.000000000 +0000
+++ /goss/centos7/goss-generated-amd64.yaml    2017-03-27 22:19:57.000000000 +0000
@@ -144,7 +144,7 @@
     filesystem: tmpfs
 http:
   http://google.com:
-    status: 301
+    status: 302
     allow-insecure: false
     no-follow-redirects: true
     timeout: 5000
````

**Comment by pysysops** [comment]
Google issues 301 to some global areas and 302 to others. I found this whilst travelling around the globe. 

Perhaps amending it to an advanced marcher might be a better idea?

**Comment by aelsabbahy** [comment]
Or using a more stable test url.

**Comment by aelsabbahy** [comment]
I'm gonna close this out for now.. feel free to re-open with more stable URLS or to create an issue out if this if you like.

**Pull request closed without merging**
