### PR TITLE
Allow log level to be set and filtering logs accordingly

### PR DESCRIPTION
**Pull request by obourdon**
##### Checklist

- [x] `make test-all` (UNIX) passes. CI will also test this
- [ ] unit and/or integration tests are included (if applicable)
- [x] documentation is changed or added (if applicable)

### Description of change

Some of the goss default logging messages might be seen as not very useful. This fix allow easy log level customisation and filtering

### CODE REVIEW

**Comment by aelsabbahy** [comment]
I haven't had a chance to go through this PR in depth, but this was a much needed feature. Many thanks for taking the time to add this!

The main thing I'll be reviewing is making sure this PR and #576 don't have major conflicts.

**Comment by obourdon** [comment]
@aelsabbahy no pb, many thanks to you for the great work

**Comment by aelsabbahy** [comment]
One of these days I need to fork the go-lang code and run code climate on it. Very curious what the results would be.

**Comment by aelsabbahy** [comment]
Which function was failing?

**Comment by obourdon** [comment]
> Which function was failing?

strangely the error was triggered by my changes in Validate but seems like other functions also had this issue without failing [see this link](https://codeclimate.com/github/aelsabbahy/goss/pull/641)

**Comment by aelsabbahy** [comment]
Took this for a spin, it's a very nice change that greatly improves debugging and can be built upon. The only thing that needs to change is that INFO is too noisy/chatty as a default.

**Comment by aelsabbahy** [comment]
Oh, and I think a small writeup on the log-levels and when they should be used would be nice, but that can be a separate PR/improvement.

**Comment by obourdon** [comment]
> Took this for a spin, it's a very nice change that greatly improves debugging and can be built upon. The only thing that needs to change is that INFO is too noisy/chatty as a default.

Understood and agreed will do the change soon (after rebased on v0.3.14)

**Comment by obourdon** [comment]
> Oh, and I think a small writeup on the log-levels and when they should be used would be nice, but that can be a separate PR/improvement.

Will do too

**Comment by obourdon** [comment]
Done with additional documentation. @aelsabbahy however, after doing so, I do not understand why you find INFO too verbose, may be just changing the default logging level to WARN instead of INFO would better match your thoughts

**Comment by obourdon** [comment]
@aelsabbahy done rebasing on latest master
Do you think you'll merge this in some future version please ?

**Comment by aelsabbahy** [comment]
```
$ goss v
2020/11/25 11:04:33 Setting log level to WARN
........

Total Duration: 0.002s
Count: 8, Failed: 0, Skipped: 0
```

**Comment by obourdon** [comment]
@aelsabbahy got it, will have a look at this later this week. Many thanks for making this way clearer

**Comment by aelsabbahy** [comment]
https://dave.cheney.net/2015/11/05/lets-talk-about-logging

This might not be a bad approach. Split logging into just two levels that are both disabled by default.. INFO and DEBUG.

Can use INFO to help users get more info regarding goss and DEBUG for more developer level debugging. But I'm open to suggestions.

**Comment by obourdon** [comment]
@aelsabbahy finally got some time to rework on this. Could you please check that the new code fullfill your requirements
I also tried to understand why the CI is failing on OSX but I do not see why `brew install bash` is failing. Many thanks in advance

**Comment by obourdon** [comment]
@aelsabbahy finally found a way to fix OSX CI by building bash homebrew formula from source. Currently trying another option

**Comment by obourdon** [comment]
@aelsabbahy both solutions work, only keeping the binary HomeBrew formula version

**Comment by obourdon** [comment]
@aelsabbahy any chance you could review and possibly integrate this soon please ?

**Comment by sebinjohn** [comment]
Is there a plan to revive this PR. I'm interested in this feature.

**Comment by obourdon** [comment]
@sebinjohn unfortunately looking at #699 and #713 the only possibility for you is to fork this PR to use it (BTW this is already what we are doing on our side for quite some time)
We were considering maintaining our own supported fork but this is completely non possible for our team at this point in time

**Comment by ripienaar** [comment]
It's unfortunate, because now there is also a sever security vulnerablity in runc that this package depends on, it's likely we will have no choice but to maintain a fork :( @obourdon @sebinjohn

**Comment by sebinjohn** [comment]
@obourdon  thanks for the info.  I will look into forking further.

**Comment by obourdon** [comment]
@sebinjohn see PR [https://github.com/goss-org/goss/pull/802](https://github.com/goss-org/goss/pull/802)

**Pull request closed without merging**
