### PR TITLE
Add "dcgoss flavour" of dgoss

### PR DESCRIPTION
**Pull request by fbartels**
I am currently playing with goss and a setup coming from docker-compose. Looking through Github I came across https://github.com/telephoneorg/dcgoss

The Dockerfile in there did not build anymore and the website of the org does not work anymore so it seems this project is not maintained any longer. So I decided to import their latest version (which seems anyways be based on dgoss, although their repo is missing a license file) and merge it with changes from dgoss.

Additionally I let it run through shellcheck and fixed some warnings.

### CODE REVIEW

**Comment by aelsabbahy** [comment]
Can you move this to a dcgoss folder and add a brief readme.md.

Doesn't have to be too detailed. The extras are really there for inspiration on ways to use goss.

**Comment by fbartels** [comment]
Hi @aelsabbahy,

sorry for the update taking so long. I have now added a readme and moved dcgoss into its own subdir.

**Comment by fbartels** [comment]
Looking into this again, should I also add this to the travis file? e.g. after https://github.com/aelsabbahy/goss/blob/master/.travis.yml#L28

**Comment by aelsabbahy** [comment]
Looks great, and no need to put it in .travis.yml. I don't think I want to package the extras folder as part of goss. dgoss is an exception currently.. but that might not always be the case.

**Pull request merged**
