### PR TITLE
Migrate imports from docker to moby

### PR DESCRIPTION
**Pull request by dacamp**

### CODE REVIEW

**Comment by dacamp** [comment]
Actually, looks like docker wants you to still import it as `github.com/docker/docker` so closing this out.

**Comment by aelsabbahy** [comment]
Can you point me to the doc on docker import for my reference.

**Comment by dacamp** [comment]
I don't have any official word from ~Docker~ Moby but their [source code](https://github.com/moby/moby/blob/master/pkg/mount/mount.go) still references the _docker/docker_ import path `package mount // import "github.com/docker/docker/pkg/mount"`

**Comment by aelsabbahy** [comment]
Thanks!

**Pull request closed without merging**
