### PR TITLE
[#524] Add Code Coverage Support

### LINKED ISSUE #524: Fail CI build if golint finds problems (non-functional)
**Describe the feature:**

Golint should find 0 problems or fail the CI build.

**Describe the solution you'd like**

While it's non-functional, it's worrying that golint finds a high quantity of problems during builds.
Since most problems seem to be documentation, it will double as a method to lower the entry barrier to understand Goss internals.

**Describe alternatives you've considered**

Some actions can be taken to minimize the issue:
- Increasing golint problem confidence. 
- Ignoring certain types of golint problems.
- Simply removing golint.

Go vet should also be enabled as part of the build.

### PR DESCRIPTION
**Pull request by pedroMMM**
##### Checklist

- [x] `make test-all` (UNIX) passes. CI will also test this
- [x] documentation is changed or added
- [x] update `CC_TEST_REPORTER_ID` with Goss token **(maintainer task)**

### Description of change

Add Code Coverage support to perform Static Code Analysis as discussed on #524. This is just the initial setup. When everyone has visibility into the code problems within Goss the contributors can see how their changes affect the overall quality and the maintainers can make informed decisions. 

**The Code Climate PR actions will only be active on PRs that are created after Code Climate is configured and this PR is merged.**

Closes #524.

### Setup Code Climate:

1. [Sign up](https://codeclimate.com/oauth_signups/new) for free to Code Climate for OSS via GitHub
2. Add the Goss Repository on the [OSS Dashboard](https://codeclimate.com/oss/dashboard)
3. Install [Code Climate GitHub App](https://github.com/apps/codeclimate)
4. Locate the `Repo Settings` menu on the [Code Climate Repo Page](https://codeclimate.com/github/aelsabbahy/goss)
5. Locate the `GitHub` menu on the `Repo Settings` page
6. Enable `Summary comments` and `Delete outdated comments and post a new one`
7. Disable `Inline issue comments`
8. Activate `Pull request status updates`
9. Install the `Webhook on GitHub` 
10. Locate the `Test coverage` menu on the `Repo Settings` page
11. Disable `Enforce Diff Coverage` and `Enforce Total Coverage` then save.
12. Generate a new `TEST REPORTER ID` and copy it
13. Replace the `CC_TEST_REPORTER_ID` in this PR's `.travis.yml` with the previous Id
14. Verify the Code Climate Webhook is installed on [GitHub](https://github.com/aelsabbahy/goss/settings/hooks)

### CODE REVIEW

**Comment by aelsabbahy** [comment]
Thank you so much for the clear instructions. They were very simple and clear to follow. I did all the steps and added a commit with  CC_TEST_REPORTER_ID as an encrypted token, not sure if that was correct or not (does encrypting it cause problems? should it be plaintext?).

I was a little confused by this:
https://github.com/codeclimate/test-reporter/blob/master/examples/go_examples.md#example-1

Do you know the best way to test this?

**Comment by aelsabbahy** [comment]
My commit seems to have triggered the codecommit message, does that look correct to you?

**Comment by pedroMMM** [comment]
> Thank you so much for the clear instructions. They were very simple and clear to follow. I did all the steps and added a commit with CC_TEST_REPORTER_ID as an encrypted token, not sure if that was correct or not (does encrypting it cause problems? should it be plaintext?).
> 
> I was a little confused by this:
> https://github.com/codeclimate/test-reporter/blob/master/examples/go_examples.md#example-1
> 
> Do you know the best way to test this?

I am not 100% sure but I think you verify if it worked by checking if the branch has produced any test report. Navigate to `Test coverage` menu on the `Repo Settings` page and check the `Recent Reports`.

> My commit seems to have triggered the codecommit message, does that look correct to you?
Yes, this is the initial problem discovery. They will have to be accepted by the maintainers. After that only new problems will show up there.

**Comment by aelsabbahy** [comment]
I'll merge this and create a dummy commit to test it out.

There might be some more tweaking to do, but this is a good start.

**Comment by pedroMMM** [comment]
> I'll merge this and create a dummy commit to test it out.
> 
> There might be some more tweaking to do, but this is a good start.
@aelsabbahy let me know if it worked well. Also, you can accept the Code Climate problems and it only cleans the PR checks but leaves the problems untouched in Code Climate.

**Pull request merged**
