### PR TITLE
[bugfix] Add Matching resource to NewGossConfig()

### LINKED ISSUE #278: matching not working
```
~/tmp
❯ goss -g ./goss.yaml v
Error: found 0 tests, source: ./goss.yaml

~/tmp
❯ cat goss.yaml
---
matching:
  has_2:
    content:
      - 2
    matches:
      contain-element: 2

~/tmp
❯ goss --version && uname -a
goss version v0.3.2
Darwin ROSELCDV0001SSU 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
```

Same with `0.3.4` am I crazy?

### PR DESCRIPTION
**Pull request by OmarDarwish**
Fixes #278

### CODE REVIEW

**Comment by aelsabbahy** [comment]
Looks good. Can you add a test for this in the integration-tests folder?

**Comment by OmarDarwish** [comment]
Added. When I ran it locally, the tests I added pass for all architectures. The only failure was for the autofs service on . It was not `running` for precise-64. Not sure why, but it seems unrelated to my changes:
```bash
++ docker_exec /goss/precise/goss-linux-amd64 --vars /goss/vars.yaml -g /goss/precise/goss.yaml validate
++ docker exec goss_int_test_precise_amd64 /goss/precise/goss-linux-amd64 --vars /goss/vars.yaml -g /goss/precise/goss.yaml validate
+ out='.........................F........................................................

Failures/Skipped:

Service: autofs: running:
Expected
    <bool>: false
to equal
    <bool>: true

Total Duration: 1.005s
Count: 82, Failed: 1, Skipped: 0'
```

**Comment by OmarDarwish** [comment]
Looks like it passed on Travis though 🤷‍♂️

**Comment by elliotweiser** [comment]
@OmarDarwish I've encountered that as well when attempting to reproduce the integration test suite on my laptop. There appear to be several differences between the Travis CI environment and Docker for Mac on a development laptop that makes it difficult to reproduce. To name a few:

* Package version differences on several docker containers
* Autofs not running on the precise container
* Archlinux not starting correctly

Definitely worth investigating, but in a separate change/thread.

**Comment by aelsabbahy** [comment]
Seen it myself (fedora laptop), haven't followed up on it. I've been using Travis CI as a source of Truth.

I'm guessing it's related to the storage driver for docker on Ubuntu.

**Pull request merged**
