### PR TITLE
Adding support to provide DNS server port

### PR DESCRIPTION
**Pull request by davidcollom**
Provide support to provide a server and port when querying DNS Servers.

**Usecase:**
Ensuring consul is performing DNS queries as expected, you may have configuration like:
```
dns:
  consul.service.consul:
    resolvable: true
    server: 127.0.0.1:8125
```

### CODE REVIEW

**Comment by aelsabbahy** [comment]
I like it, LGTM once the build is succeeding

**Comment by davidcollom** [comment]
I wasn't able to get the tests passing, as you can see from efc748ccd5df4f1c74e7bddcdc6faaffa99ccd21 and afe3cd856c009d2707e5be14a45c6a90b4bbfae8.

It looks as though the wheezy repository has moved on since the last docker build.
I also noticed a number of other open PR's with similar issues, leading me to believe this is not related to my change.

I'm happy to have another look into it, but building the images locally and running the tests pass.

**Comment by davidcollom** [comment]
@aelsabbahy - Any chance we can get this merged also? now that #382 has been merged all tests are now passing!

**Comment by aelsabbahy** [comment]
@davidcollom Tested this locally, it doesn't seem to work when defining the port.

Can you provide a working example of a test explicitly setting `:53`?

This works:
```
dns:                                                                                                                                                                                           
  dnstest.io:                                                                                                                                                                                  
    resolvable: true                                                                                                                                                                           
    addrs:                                                                                                                                                                                     
    - 192.30.252.153                                                                                                                                                                           
    - 192.30.252.154                                                                                                                                                                           
    timeout: 500                                                                                                                                                                               
    server: 8.8.8.8
```
This does not:
```
dns:                                                                                                                                                                                           
  dnstest.io:                                                                                                                                                                                  
    resolvable: true                                                                                                                                                                           
    addrs:                                                                                                                                                                                     
    - 192.30.252.153                                                                                                                                                                           
    - 192.30.252.154                                                                                                                                                                           
    timeout: 500                                                                                                                                                                               
    server: 8.8.8.8
```

```
$ goss v
FS

Failures/Skipped:

DNS: dnstest.io: resolvable:
Expected
    <bool>: false
to equal
    <bool>: true
DNS: dnstest.io: addrs: skipped

Total Duration: 0.005s
Count: 2, Failed: 1, Skipped: 1

```

**Comment by davidcollom** [comment]
Hi, I've not had things checked out for a while, it could take me a few
days to get round to this, I do have example services already deployed
which should help with reproducing.

**Comment by aelsabbahy** [comment]
No biggie, few things things:

1. I would drop the dockerfile/md5 changes from this PR.

2. I'm 90% sure the issue is that it used 8.8.8.8:53 as the server, and then 53 as the port. Server needs to be parsed correctly.

3. Can you update one of the goss-shared examples with the new syntax so CI can validate that both are working?

**Comment by davidcollom** [comment]
Hey @aelsabbahy, I've taken a quick look at this today, and believe I've resolved the outstanding issues.

Here's my test goss file:
```
dns:
  google.com:
    resolvable: true
    server: 192.168.1.23:53

  www.bbc.co.uk:
    resolvable: true
    server: 192.168.1.23

  plex.home.collom.co.uk:
    resolvable: true
    server: 192.168.1.10

  consul.service.consul:
    resolvable: true
    server: 127.0.0.1:8600
```

For the consul check, I was able to start a dev server via: `docker run -d -p 8600:8600/udp -p 8600:8600/tcp consul`

I also added some unit tests (first time in Go) to ensure that this was working as we expected.

It looks like the CI tests are failing again though 😭 Seemingly about Wheezy and package versions again.

**Comment by davidcollom** [comment]
Hey @aelsabbahy, I've taken a quick look at this today, and believe I've resolved the outstanding issues.

Here's my test goss file:
```
dns:
  google.com:
    resolvable: true
    server: 192.168.1.1:53

  www.bbc.co.uk:
    resolvable: true
    server: 192.168.1.1

  edition.cnn.com:
    resolvable: true
    server: 192.168.1.1

  consul.service.consul:
    resolvable: true
    server: 127.0.0.1:8600
```

For the consul check, I was able to start a dev server via: `docker run -d -p 8600:8600/udp -p 8600:8600/tcp consul`

I also added some unit tests (first time in Go) to ensure that this was working as we expected.

~It looks like the CI tests are failing again though 😭 Seemingly about Wheezy and package versions again.~ Looks like the latest build passed! 🎉

**Comment by aelsabbahy** [comment]
Eyeball/CI looks great. Appreciate you taking the time to implement this!

Thanks for adding unit tests!

I'll review this more in depth this weekend.

**Comment by aelsabbahy** [comment]
Thank you for your contribution!

**Pull request merged**
