### PR TITLE
Issue 493 Change permission from tmp_dir so less privileged user can …

### PR DESCRIPTION
**Pull request by racarvalho1987**
…run goss

Include a chmod 644 to set read permission from any user that runs the goss tests.

Let me know if there is something else that I need to do.

### CODE REVIEW

**Comment by aelsabbahy** [comment]
Thinking the chmod makes more sense around line 33. For everything below the folder to not conflict with line 29.

**Comment by aelsabbahy** [comment]
Fixes #493

**Comment by racarvalho1987** [comment]
I did a commit to change the line but it won't work
Wait a moment please, I am working on it

**Comment by aelsabbahy** [comment]
Yeah, Ideally goss binary should be 755, all other files 644.

Maybe chmod -R a+r $tmp_dir?

**Comment by aelsabbahy** [comment]
Looks good on a quick eyeball check. I'll test it later today and merge.

**Comment by racarvalho1987** [comment]
Ok @aelsabbahy thanks !

**Pull request merged**
